In [15]:
# 코드 실행에 필요한 라이브러리를 미리 import.
import torch
import numpy as np

from copy import deepcopy

# a_tensor_initialization

In [16]:
# 자료형 기본값: float32
t1 = torch.Tensor([1, 2, 3], device='cpu')      # cpu 위에서 연산함에 유의.
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# 아래와 같이 cpu/gpu 간 상호 변환 가능.
try:
    t1_cpu = t1.cpu()
    t1_cuda = t1.cuda()
except:
    print('no gpu has found')

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
no gpu has found


In [17]:
# 자료형 기본값: float32
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [18]:
# 스칼라.
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

torch.Size([]) 0


In [19]:
a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [20]:
a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [21]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [22]:
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [23]:
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [24]:
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [25]:
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [26]:
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [27]:
a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


In [28]:
a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

torch.Size([4, 1, 5]) 3


In [29]:
# torch가 예상한 텐서 크기는 (4, 1, 2, 3)이지만 dim3에서 크기가 3인 값을 받음.
try:
    a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
        [[[1, 2, 3], [4, 5]]],
        [[[1, 2, 3], [4, 5]]],
        [[[1, 2, 3], [4, 5]]],
        [[[1, 2, 3], [4, 5]]],
    ])
except:
    print('tensor size does not match')

tensor size does not match


# b_tensor_initialization_copy

In [30]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

# 각각의 텐서는 원본 배열을 복사해 생성됨.
# 즉, 원본을 수정해도 복사된 텐서는 변하지 않음.
l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [31]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

# 넘파이 배열도 기본적으로 복사 후 텐서를 생성함.
# 단, as_tensor로 불러오면 참조로 생성함.
# 즉, 원본 넘파이 배열을 수정하면 텐서도 변경됨.
l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


# c_tensor_initialization_constant_values

In [32]:
# size 크기의 텐서를 1로 초기화.
t1 = torch.ones(size=(5,))  # or torch.ones(5)

# input과 동일한 크기의 텐서를 1로 초기화.
t1_like = torch.ones_like(input=t1)

print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [33]:
# 상동. 단, 1 대신 0으로 초기화.
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [34]:
# 상동. 단, 초기화되지 않은 쓰레기값이 들어갈 수 있음.
# ref: https://docs.pytorch.org/docs/stable/generated/torch.empty.html
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

tensor([-1.8891e+26,  6.0240e-01,  0.0000e+00,  0.0000e+00])
tensor([3.0000, 2.1250, 0.0000, 0.0000])


In [35]:
# n * n 크기의 단위 행렬 생성.
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values

In [36]:
# 정수 난수. [low, high)
t1 = torch.randint(low=10, high=20, size=(1, 2))

# Uniform Distribution 실수 난수. [0, 1)
t2 = torch.rand(size=(1, 3))

# Strandard Normal Distribution 실수 난수. mean = 0, var = 1
t3 = torch.randn(size=(1, 3))

# Normal Distribution 실수 난수.
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))

# 선형 보간.
t5 = torch.linspace(start=0.0, end=5.0, steps=3)

# 파이썬의 range와 유사.
t6 = torch.arange(5)

print(t1)
print(t2)
print(t3)
print(t4)
print(t5)
print(t6)

tensor([[19, 10]])
tensor([[0.0119, 0.3332, 0.1063]])
tensor([[-0.2076,  2.5224,  0.7758]])
tensor([[ 9.0772,  9.3097],
        [11.6420,  8.0570],
        [11.7601,  7.8469]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [37]:
# 파이썬의 range는 실수 입력을 받지 않음.
try:
    print(range(0, 3.14, 2.71))
except:
    print('range does not accept real numbers')
    
# torch의 arange는 실수 입력을 받음.
print(torch.arange(0, 3.14, 2.71))

range does not accept real numbers
tensor([0.0000, 2.7100])


In [38]:
# 수동으로 난수 생성 시드를 설정할 수 있음.
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [39]:
# 이전 셀과 동일한 출력을 확인할 수 있음.
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion

In [40]:
a = torch.ones((2, 3))                                  # 기본 자료형: float32
                                                        # 기본 자료형은 전역 기본 자료형을 사용한다.
                                                        # 이때 전역 기본 자료형은 최초 설치 시 float32로 설정된다.
                                                        # ref: https://docs.pytorch.org/docs/main/generated/torch.ones.html
                                                        #      https://docs.pytorch.org/docs/main/generated/torch.set_default_dtype.html#torch.set_default_dtype
b = torch.ones((2, 3), dtype=torch.int16)
c = torch.rand((2, 3), dtype=torch.float64) * 20.
d = b.to(torch.int32)       # b를 int32로 변환.

print(a.dtype)
print(b)
print(c)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [41]:
double_d = torch.ones(10, 2, dtype=torch.double)     # float64
short_e = torch.tensor([[1, 2]], dtype=torch.short)  # int16

double_d = torch.zeros(10, 2).double()      # float32 -> float64
short_e = torch.ones(10, 2).short()         # float32 -> int16

# 상동. 다른 방법.
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

# 상동. 다른 방법.
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

# 참고: 기본 자료형은 float32.
double_d = torch.zeros(10, 2)
short_e = torch.ones(10, 2)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16
torch.float32
torch.float32


In [42]:
# 연산 시 자동 형변환.
# float64와 int16 중 더 넓은 도메인을 갖는 쪽으로 변환.
# 따라서, float64 * int16 -> float64
#
# 파이토치는 C++ 기반이므로 C++의 자동 형변환 규칙을 따를 것으로 예상됨.
# 참고: intx, inty -> intx (x > y)
#       floatx, floaty -> floatx (x > y)
#       signed, unsigned -> unsigned
#       integer, float -> float
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


# f_tensor_operations

In [43]:
# 사칙 연산은 member-wise로 수행됨.
# e.g. [1, 2] + [3, 4] = [4, 6]
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2        # 참고: 연산자 재정의로 add를 사용하지 않고 연산자를 사용할 수 있다.

print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [44]:
# 뺄셈, 곱셈, 나숫셈도 상동.
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [45]:
# member-wise이므로 두 텐서의 크기가 다르면 오류.
try:
    x1 = torch.ones(size=(2, 4))
    x2 = torch.ones(size=(2, 3))
    x3 = x1 + x2
except:
    print('tensor size does not match')

tensor size does not match


In [46]:
# member-wise이므로 아래와 같이 내적을 구하는 데 사용할 수 있다.
v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

print(sum(v1.mul(v2)))
print(sum(v1 * v2))
print(v1.dot(v2))     # 물론 파이토치에는 내적을 구하는 함수가 별도로 존재한다.

tensor(11)
tensor(11)
tensor(11)


# g_tensor_operations_mm

In [47]:
# 내적 연산.
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)

# 내적의 결과는 스칼라이므로 크기는 []가 됨.
print(t1, t1.size())

tensor(7) torch.Size([])


In [48]:
# 텐서의 행렬곱 연산.
# 행렬곱이므로 텐서의 크기는 (n, m) * (m, k)여야 함.
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


In [49]:
# 행렬곱 연산이지만 batch 처리.
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)

print(t7.size())

# 아래 두 코드는 동등한 효과를 갖는다.
torch_batched = torch.bmm(t5, t6)
manually_batched = torch.stack([torch.mm(x, y) for x, y in zip(t5, t6)])

# 부동소수점 자료형이므로 eps를 도입하여 값 비교.
print(torch.all(torch_batched - manually_batched) < 1e-5)

torch.Size([10, 3, 5])
tensor(True)


# h_tensor_operations_matmut

In [50]:
# ref: https://docs.pytorch.org/docs/stable/generated/torch.matmul.html

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

torch.Size([])


In [51]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# 행렬 * 벡터 -> 행렬 * 열벡터로 간주함.

torch.Size([3])


In [52]:
# vector x matrix: broadcasted dot
x = torch.randn(3)
y = torch.randn(3, 4)
print(torch.matmul(x, y).size())  # torch.Size([3])

# 벡터 * 행렬 -> 행벡터 * 행렬로 간주함.

torch.Size([4])


In [53]:
# 이외의 3차원 이상의 텐서가 주어지면 batch 처리함.

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


# i_tensor_broadcasting

In [54]:
# broadcasting이란?
#     서로 다른 크기를 갖는 두 텐서의 연산을 가능케 하기 위해 텐서의 크기를 변형하는 것.
#     ref: https://docs.pytorch.org/docs/stable/notes/broadcasting.html
#
#     Each tensor has at least one dimension.
#     When iterating over the dimension sizes, starting at the trailing dimension, the dimension sizes must either be equal, one of them is 1, or one of them does not exist.

t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0

# [1, 2, 3] * 2
# -> [1, 2, 3] * [2, 2, 2]
# -> [2, 4, 6]
print(t1 * t2)
print((t1 * t2).size())

tensor([2., 4., 6.])
torch.Size([3])


In [55]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])

# [
#     [0, 1],
#     [2, 4],    -  [4, 5]
#     [10, 10],
# ]
# ->
# [                 [
#     [0, 1],           [4, 5],
#     [2, 4],    -      [4, 5],
#     [10, 10],         [4, 5],
# ]                 ]
# ->
# [
#     [-4, -5],
#     [-2, -1],
#     [6, 5],
# ]
print(t3 - t4)
print((t3 - t4).size())

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
torch.Size([3, 2])


In [56]:
# 상동.
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [57]:
# 스칼라로 나누므로 x가 텐서여도 broadcasting되어 연산 가능.
def normalize(x):
    return x / 255

t6 = torch.randn(3, 28, 28)
print(normalize(t6).size())

torch.Size([3, 28, 28])


In [58]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])

# (2, 2) + (1, 2) -> (2, 2)
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])

# (2, 2) + (2, 1) -> (2, 2)
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])

# (1, 2) + (2, 1) -> (2, 2)
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])

# (2, 2) + (1) -> (2, 2)
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [59]:
# (4, 3, 2) * (3, 2) -> (4, 3, 2)
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

# (4, 3, 2) * (3, 1) -> (4, 3, 2)
t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

# (4, 3, 2) * (1, 2) -> (4, 3, 2)
t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

# (5, 3, 4, 1) + (3, 1, 1) -> (5, 3, 4, 1)
t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [60]:
# (5, 1, 4, 1) + (3, 1, 1) -> (5, 3, 4, 1)
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1])

# (1) + (3, 1, 7) -> (3, 1, 7)
t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

# (3, 3, 3) + (3, 1, 3) -> (3, 3, 3)
t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

try:
    t25 = torch.empty(5, 2, 4, 1)
    t26 = torch.empty(3, 1, 1)
    print((t25 + t26).size())
except:
    print('(5, <2>, 4, 1) + (<3>, 1, 1) -> (5, <x>, 4, 1)')
    print('2 and 1 is not equal in dim 1')

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
(5, <2>, 4, 1) + (<3>, 1, 1) -> (5, <x>, 4, 1)
2 and 1 is not equal in dim 1


In [61]:
# (4) * sclar -> (4)
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

# (4) ^ scalar -> (4)
t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

# (4) ^ (4) -> (4)
exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing

In [62]:
# size: (3, 5)
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

# dim0의 원소 중 하나를 택했으므로 dim0의 차원이 사라진다.
# (3, 5) -> (5)
# 이때 dim0의 1번째 요소를 택하므로 2번 행이 선택된다.
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])

# dim0의 원소는 모두 택하고 dim1의 원소는 하나만 택하므로 dim1의 차원이 사라진다.
# (3, 5) -> (3)
# 이때 각 행에서 1번째 요소를 택하므로 1번째 열이 선택된다.
print(x[:, 1])  # >>> tensor([1, 6, 11])

# dim0와 dim1에서 전부 하나의 원소만 택하므로 두 차원이 모두 사라진다.
# (3, 5) -> [] (스칼라)
# 이때 x[1, 2]는 이차원 배열에서 x[1][2]와 동등한 의미를 가지므로 7이 선택된다.
print(x[1, 2])  # >>> tensor(7)

# dim0의 원소는 모두 택하고 dim1의 원소는 하나만 택하므로 dim1의 차원이 사라진다.
# (3, 5) -> (3)
# 이때 dim1에서 마지막 원소를 택하므로 마지막 열이 선택된다.
print(x[:, -1])  # >>> tensor([4, 9, 14)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [63]:
y = torch.zeros((6, 6))

# y에서 dim0은 [1, 4), dim2는 2번째만 택한다.
# (6, 6) -> (3)
# 이때 dim0가 [1, 4)로 변화하고 dim2는 2로 고정이므로 2번째 열의 [1, 4) 구간의 행이 선택된다.
y[1:4, 2] = 1

print(y[1:4, 2])
print(y[1:4, 2].size())
print(y)

# 두 차원 모두 [1, 4) 구간을 택한다.
# (6, 6) -> (3, 3)
print(y[1:4, 1:4])

tensor([1., 1., 1.])
torch.Size([3])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [64]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)

# z[0][0]부터 z[1][-1]까지.
print(z[:2])

# z[1][1]부터 z[-1][2]까지.
print(z[1:, 1:3])

# z[0][1]부터 z[-1][-1]까지.
print(z[:, 1:])

# z[1][1]부터 z[-1][2]까지.
z[1:, 1:3] = 0

print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


In [65]:
# 기본적으로 n차원이 있는 텐서에서,

# : -> for index in range(len(t))
# a: -> for index in range(a, -1)
# :b -> for index in range(b)
# a:b -> for index in range(a, b)

# e.g.
view = torch.tensor([
    [1, 2],
    [3, 4]
])

# 두 텐서가 있을 때,
t1 = torch.zeros((6, 6, 6))
t2 = torch.zeros((6, 6, 6))

# 이러한 슬라이싱은,
t1[2:4, 3, 4:] = view

# c.f.
try:
    t1[2:4][3][4:] = view
except:
    print('index out of bound: t[2:4] has size of (2, 6, 6)')

# 아래의 반복문과 동치임.
for i in range(2, 4):
    j = 3
    for k in range(4, len(t2[i, j])):
        t2[i, j, k] = view[i - 2][k - 4]
        
print(torch.all(abs(t1 - t2) < 1e-5))

index out of bound: t[2:4] has size of (2, 6, 6)
tensor(True)


# k_tensor_reshaping

In [66]:
# c.f. array_view_t
# typedef struct {
#     int* arr;
#     size_t rows;
#     size_t cols;
#     size_t stride;
# } array_view;

# 모든 데이터는 근본적으로 메모리에서 일차원적으로 저장됨.
# n차원 배열 또는 텐서는 이를 바라보는 관점의 차이로 볼 수 있음.
# t1은 메모리에서 `1, 2, 3, 4, 5, 6`
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# {
#     .data = t1,
#     .rows = 3,
#     .cols = 2,
#     .stride = 2,
# }
t2 = t1.view(3, 2)  # Shape becomes (3, 2)

# {
#     .data = t1,
#     .rows = 1,
#     .cols = 6,
#     .stride = 6,
# }
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)

print(t2)
print(t3)

# 상동.
t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)

# reshape를 해도 원소의 총 개수는 변하지 않음에 유의.
# 데이터는 그대로이고 *읽는 관점*을 변경하는 것.

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [67]:
# squeeze는 원소의 개수가 1인 차원의 원소에서 []를 제거한다.
# e.g.
#     x = [ [[[...]]], [[...]], ...] ]
#       -> x
#       -> [[[[...]]], [[...]], ...]

# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,) -> dim 중에서 원소의 개수가 1인 차원을 모두 제거.
                   # 즉, 크기에서 1을 모두 제거.

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7)
print(t8)

print(t6.squeeze(0).shape) # (1, 3, 1) -> (3, 1)
print(t6.squeeze(1).shape) # (1, 3, 1) -> (1, 3, 1) :: dim1은 원소의 개수가 3으로 squeeze되지 않는다.
print(t6.squeeze(2).shape) # (1, 3, 1) -> (1, 3)

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])
torch.Size([1, 3, 1])
torch.Size([1, 3])


In [68]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
# 대상 dim을 통째로 [] 안에 넣는다고 생각하면 됨.
# e.g.
#     x = [[[[...]]], [[...]], ...]
#       -> [x]
#       -> [ [[[[...]]], [[...]], ...] ]
t10 = t9.unsqueeze(0)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)

# (2, 3)에서 dim1 즉, 3 앞에 1을 추가. (또는 3를 [] 안에 넣음.)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3)
print(t12, t12.shape)

tensor([[1, 2, 3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [69]:
# 배열을 1차원으로 바꿈.

# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

# start_dim을 설정하면 상위의 차원은 flatten되지 않음.
# *end_dim 인자도 있다.
t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [70]:
# 차원 순서 바꾸기.
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# 두 차원을 전치.
# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)
print(t22)

# eqv: torch.transpose(t19, 0, 1)
t23 = torch.t(t19)  # Shape becomes (3, 2)
print(t23)

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat

In [71]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

#     dim1 1 + 3 + 2 = 6
#     v
# (2, 1, 3)
# (2, 3, 3)
# (2, 2, 3)
# => (2, 6, 3)
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)

# 참고: dim의 기본 파라미터는 0임.
#      모든 dim을 cat하는 것이 아님.

# concat을 위해서 cat의 대상 dim을 제외한 모든 dim의 크기가 같아야 함.
# 또는 길이가 0인 일차원 텐서.

torch.Size([2, 6, 3])


In [72]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

# 일차원 텐서는 일반적인 리스트의 + 연산과 동일함.
l5 = list(range(0, 3))  # [0, 1, 2]
l6 = list(range(3, 8))  # [3, 4, 5, 6, 7]

l7 = l5 + l6
print(len(l7))  # >>> 8
print(l7)       # >>> [0, 1, 2, 3, 4, 5, 6, 7]

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
8
[0, 1, 2, 3, 4, 5, 6, 7]


In [73]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])
# => dim0에서 병합하므로 [(3,), (3,)] + [(3,), (3,)] 꼴이 된다.

t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])
# => dim1에서 병합하므로 [[(3,) + (3,)], [(3,) + (3,)]] 꼴이 된다.

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [74]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])
# => dim0에서 병합하므로 [(3,), (3,), (3,)] + [(3,), (3,), (3,)] 꼴이 된다.

t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
# => dim1에서 병합하므로 [[(3,) + (3,) + (3,)], [(3,) + (3,) + (3,)]] 꼴이 된다.

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [75]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

l17 = [[
    [0, 1, 2],
    [3, 4, 5],
]]
l18 = [[
    [6, 7, 8],
    [9, 10, 11],
]]

# 각각 아래와 동치.

l19 = deepcopy(l17)
#dim0에서 병합.
l19 += l18

l20 = deepcopy(l17)
# dim0
for i in range(1):
    # dim1에서 병합.
    l20[i] += l18[i]

l21 = deepcopy(l17)
# dim0
for i in range(1):
    # dim1
    for j in range(2):
        # dim2에서 병합.
        l21[i][j] += l18[i][j]
    
print(torch.all(torch.tensor(l19) - t19 < 1e-5))
print(torch.all(torch.tensor(l20) - t20 < 1e-5))
print(torch.all(torch.tensor(l21) - t21 < 1e-5))

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])
tensor(True)
tensor(True)
tensor(True)
