In [1]:
# 코드 실행에 필요한 라이브러리를 미리 import.
import torch
import numpy as np

# a_tensor_initialization

In [2]:
# 자료형 기본값: float32
t1 = torch.Tensor([1, 2, 3], device='cpu')      # cpu 위에서 연산함에 유의.
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

# 아래와 같이 cpu/gpu 간 상호 변환 가능.
try:
    t1_cpu = t1.cpu()
    t1_cuda = t1.cuda()
except:
    print('no gpu has found')

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])
no gpu has found


In [3]:
# 자료형 기본값: float32
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [4]:
# 스칼라.
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

torch.Size([]) 0


In [5]:
a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

torch.Size([1]) 1


In [6]:
a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

torch.Size([5]) 1


In [7]:
a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

torch.Size([5, 1]) 2


In [8]:
a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

torch.Size([3, 2]) 2


In [9]:
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

torch.Size([3, 2, 1]) 3


In [10]:
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

torch.Size([3, 1, 2, 1]) 4


In [11]:
a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)

torch.Size([3, 1, 2, 3]) 4


In [12]:
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

torch.Size([3, 1, 2, 3, 1]) 5


In [13]:
a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

torch.Size([4, 5]) 2


In [14]:
a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

torch.Size([4, 1, 5]) 3


In [15]:
# torch가 예상한 텐서 크기는 (4, 1, 2, 3)이지만 dim3에서 크기가 3인 값을 받음.
try:
    a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
        [[[1, 2, 3], [4, 5]]],
        [[[1, 2, 3], [4, 5]]],
        [[[1, 2, 3], [4, 5]]],
        [[[1, 2, 3], [4, 5]]],
    ])
except:
    print('tensor size does not match')

tensor size does not match


# b_tensor_initialization_copy

In [16]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

# 각각의 텐서는 원본 배열을 복사해 생성됨.
# 즉, 원본을 수정해도 복사된 텐서는 변하지 않음.
l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [17]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

# 넘파이 배열도 기본적으로 복사 후 텐서를 생성함.
# 단, as_tensor로 불러오면 참조로 생성함.
# 즉, 원본 넘파이 배열을 수정하면 텐서도 변경됨.
l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([100,   2,   3])


# c_tensor_initialization_constant_values

In [18]:
# size 크기의 텐서를 1로 초기화.
t1 = torch.ones(size=(5,))  # or torch.ones(5)

# input과 동일한 크기의 텐서를 1로 초기화.
t1_like = torch.ones_like(input=t1)

print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])


In [19]:
# 상동. 단, 1 대신 0으로 초기화.
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])


In [20]:
# 상동. 단, 초기화되지 않은 쓰레기값이 들어갈 수 있음.
# ref: https://docs.pytorch.org/docs/stable/generated/torch.empty.html
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([0., 0., 0., 0.])
print(t3_like)  # >>> tensor([0., 0., 0., 0.])

tensor([1.5901e-21, 3.0941e-41, 0.0000e+00, 0.0000e+00])
tensor([4.9028e-22, 3.0941e-41, 0.0000e+00, 0.0000e+00])


In [21]:
# n * n 크기의 단위 행렬 생성.
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values

In [22]:
# 정수 난수. [low, high)
t1 = torch.randint(low=10, high=20, size=(1, 2))

# Uniform Distribution 실수 난수. [0, 1)
t2 = torch.rand(size=(1, 3))

# Strandard Normal Distribution 실수 난수. mean = 0, var = 1
t3 = torch.randn(size=(1, 3))

# Normal Distribution 실수 난수.
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))

# 선형 보간.
t5 = torch.linspace(start=0.0, end=5.0, steps=3)

# 파이썬의 range와 유사.
t6 = torch.arange(5)

print(t1)
print(t2)
print(t3)
print(t4)
print(t5)
print(t6)

tensor([[12, 17]])
tensor([[0.0089, 0.3082, 0.7882]])
tensor([[ 0.0400, -0.1004,  0.9360]])
tensor([[10.2942,  9.9796],
        [10.6185,  9.2820],
        [ 9.4304,  9.7378]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [23]:
# 파이썬의 range는 실수 입력을 받지 않음.
try:
    print(range(0, 3.14, 2.71))
except:
    print('range does not accept real numbers')
    
# torch의 arange는 실수 입력을 받음.
print(torch.arange(0, 3.14, 2.71))

range does not accept real numbers
tensor([0.0000, 2.7100])


In [24]:
# 수동으로 난수 생성 시드를 설정할 수 있음.
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [25]:
# 이전 셀과 동일한 출력을 확인할 수 있음.
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


# e_tensor_type_conversion

In [26]:
a = torch.ones((2, 3))                                  # 기본 자료형: float32
                                                        # 기본 자료형은 전역 기본 자료형을 사용한다.
                                                        # 이때 전역 기본 자료형은 최초 설치 시 float32로 설정된다.
                                                        # ref: https://docs.pytorch.org/docs/main/generated/torch.ones.html
                                                        #      https://docs.pytorch.org/docs/main/generated/torch.set_default_dtype.html#torch.set_default_dtype
b = torch.ones((2, 3), dtype=torch.int16)
c = torch.rand((2, 3), dtype=torch.float64) * 20.
d = b.to(torch.int32)       # b를 int32로 변환.

print(a.dtype)
print(b)
print(c)
print(d)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [27]:
double_d = torch.ones(10, 2, dtype=torch.double)     # float64
short_e = torch.tensor([[1, 2]], dtype=torch.short)  # int16

double_d = torch.zeros(10, 2).double()      # float32 -> float64
short_e = torch.ones(10, 2).short()         # float32 -> int16

# 상동. 다른 방법.
double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

# 상동. 다른 방법.
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2).type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

# 참고: 기본 자료형은 float32.
double_d = torch.zeros(10, 2)
short_e = torch.ones(10, 2)

print(double_d.dtype)
print(short_e.dtype)

torch.float64
torch.int16
torch.float32
torch.float32


In [28]:
# 연산 시 자동 형변환.
# float64와 int16 중 더 넓은 도메인을 갖는 쪽으로 변환.
# 따라서, float64 * int16 -> float64
#
# 파이토치는 C++ 기반이므로 C++의 자동 형변환 규칙을 따를 것으로 예상됨.
# 참고: intx, inty -> intx (x > y)
#       floatx, floaty -> floatx (x > y)
#       signed, unsigned -> unsigned
#       integer, float -> float
double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float64


# f_tensor_operations

In [29]:
# 사칙 연산은 member-wise로 수행됨.
# e.g. [1, 2] + [3, 4] = [4, 6]
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2        # 참고: 연산자 재정의로 add를 사용하지 않고 연산자를 사용할 수 있다.

print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [30]:
# 뺄셈, 곱셈, 나숫셈도 상동.
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [31]:
# member-wise이므로 두 텐서의 크기가 다르면 오류.
try:
    x1 = torch.ones(size=(2, 4))
    x2 = torch.ones(size=(2, 3))
    x3 = x1 + x2
except:
    print('tensor size does not match')

tensor size does not match


In [32]:
# member-wise이므로 아래와 같이 내적을 구하는 데 사용할 수 있다.
v1 = torch.tensor([1, 2])
v2 = torch.tensor([3, 4])

print(sum(v1.mul(v2)))
print(sum(v1 * v2))
print(v1.dot(v2))     # 물론 파이토치에는 내적을 구하는 함수가 별도로 존재한다.

tensor(11)
tensor(11)
tensor(11)


# g_tensor_operations_mm

In [33]:
# 내적 연산.
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)

# 내적의 결과는 스칼라이므로 크기는 []가 됨.
print(t1, t1.size())

tensor(7) torch.Size([])


In [34]:
# 텐서의 행렬곱 연산.
# 행렬곱이므로 텐서의 크기는 (n, m) * (m, k)여야 함.
t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


In [35]:
# 행렬곱 연산이지만 batch 처리.
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)

print(t7.size())

# 아래 두 코드는 동등한 효과를 갖는다.
torch_batched = torch.bmm(t5, t6)
manually_batched = torch.stack([torch.mm(x, y) for x, y in zip(t5, t6)])

# 부동소수점 자료형이므로 eps를 도입하여 값 비교.
print(torch.all(torch_batched - manually_batched) < 1e-5)

torch.Size([10, 3, 5])
tensor(True)


# h_tensor_operations_matmut

In [36]:
# ref: https://docs.pytorch.org/docs/stable/generated/torch.matmul.html

# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

torch.Size([])


In [37]:
# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# 행렬 * 벡터 -> 행렬 * 열벡터로 간주함.

torch.Size([3])


In [38]:
# vector x matrix: broadcasted dot
x = torch.randn(3)
y = torch.randn(3, 4)
print(torch.matmul(x, y).size())  # torch.Size([3])

# 벡터 * 행렬 -> 행벡터 * 행렬로 간주함.

torch.Size([4])


In [39]:
# 이외의 3차원 이상의 텐서가 주어지면 batch 처리함.

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([10, 3, 5])
torch.Size([10, 3, 5])
